# Array of concepts
concepts = [
    "Self-Confidence",
    "Leadership",
    "Creative Vision",
    "Em Growth",
    "Determination",
    "Problem Solving",
    "Teamwork",
    "Goal Setting",
    "Adaptability",
    "Critical Think",
    "Curiosity",
    "Public Speaking",
    "Risk Taking",
    "Resilience",
    "Stress Mngmt",
    "Innovation",
    "Time Management",
    "Learn New Skills",
    "Collaboration",
    "Self-Motivation",
    "Patience",
    "Detail Oriented",
    "Empathy",
    "Conflict Res",
    "Active Listening",
    "Creativity",
    "Self-Discipline",
    "Strategic Think",
    "Confidence",
    "Accountability",
    "Gratitude",
    "Perseverance",
    "Work-Life Balance",
    "Honesty",
    "Positivity",
    "Self-Control",
    "Mindfulness",
    "Optimism",
    "Negotiation",
    "Influence",
    "Em Control",
    "Focus",
    "Self-Belief",
    "Decision Making",
    "Em Healing",
    "Work Ethic",
    "Resourcefulness",
    "Visionary Ideas",
    "Org Skills",
    "Persistence",
    "Ambition",
    "Compassion",
    "Assertiveness",
    "Trustworthiness",
    "Calmness",
    "Passion for Work",
    "Skill Mastery",
    "Leader Skills",
    "Goal Achieve",
    "Flexibility",
    "Entrepreneurship",
    "Self-Expression",
    "People Skills",
    "Success Oriented",
    "Charisma",
    "Career Growth",
    "Relation Build",
    "Problem ID",
    "Self-Improve",
    "Mental Agility",
    "Visionary Leader",
    "Creative Problem",
    "Drive for Success",
    "Social Resp",
    "Build Trust",
    "Collab Mastery",
    "Courage",
    "Ab. Resilience",
    "Artistic Talent",
    "Clear Purpose",
    "Empower Others",
    "Creative Expl",
    "Construct Crit",
    "Self-Leadership",
    "Conflict Manage",
    "Lead by Example",
    "Em Change",
    "Em Intelligence",
    "Growth Mindset",
    "Pos Self-Talk",
    "Physical Endur",
    "Life Planning",
    "Career Dev",
    "Visionary Think",
    "Confident Action",
    "Conflict Mediate",
    "Nav Uncertainty",
    "Balance Priors",
    "Am. Resilience",
    "Skill Development",
    "Motivate Others",
    "Adapt Leadership",
    "Achieve Goals",
    "Build Relations",
    "Self-Discovery",
    "Resource Think",
    "Coaching Skills",
    "Strength of Will",
    "Ambition&Drive",
    "Innovate Mindset",
    "Sustain Success",
    "Mental Toughness",
    "Decisive",
    "Empowerment",
    "Handle Pressure",
    "Create Opportun",
    "Inner Strength",
    "Analytic Think",
    "Inspir Ideas",
    "Self-Reliance",
    "Em Mastery",
    "Initiative",
    "Pragmatic Solns",
    "Adapt Focus",
    "Networking",
    "Personal Fulfill",
    "Em Fortitude",
    "Strategic Exec",
    "Intuit Judgment",
    "Self-Awareness",
    "Empathy Skills",
    "Em. Balance",
    "Active Listening",
    "Social Cues",
    "Self-Regulation",
    "Em. Clarity",
    "Self-Reflection",
    "Kindness Act",
    "Conflict Control",
    "Positive Framing",
    "Empathy Mapping",
    "Em. Resets",
    "Set Boundaries",
    "Assertiveness",
    "Open-Mindedness",
    "Empathic Concern",
    "Calm Under Stress",
    "Em. Space",
    "Supportive Voice",
    "Em. Words",
    "Deep Listening",
    "Nonverbal Cues",
    "Perspective Take",
    "Gratitude Focus",
    "Construct. Talk",
    "Trust Building",
    "Stress Awareness",
    "Mood Management",
    "Confidence Boost",
    "Ready to change",
    "Em. Anchor",
    "Pos. Feedback",
    "Active Empathy",
    "Healthy Detach",
    "Em. Freedom",
    "Mindful Presence",
    "Patience Practice",
    "Stress Tolerance",
    "Encourage Others",
    "Em. Healing",
    "Self-Compassion",
    "Em. Resilience",
    "De-escalation",
    "Listen Mindfully",
    "Cognitive Empathy",
    "Mediation",
    "Em. Boundaries",
    "Inner Calm",
    "Constr Criticism",
    "Empathy Connect",
    "Social Awareness",
    "Empathy Care",
    "Em. Contagion",
    "Em. Mastery",
    "Healthy Express.",
    "Support Network",
    "Inner Strength",
    "Thought Reframe",
    "Value Alignment",
    "Kindness Focus",
    "Balanced Thinking",
    "Gratitude Practice",
    "Energy Regulation",
    "Em. Diffusion",
    "Expand Empathy"
]